version: "3"
services:
  mongodb:
    image: mongo:3.4.7
    command: mongod --auth --smallfiles
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
  db_seed:
    build: ./mongo-seed
    links:
      - mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "password"
      MONGODB_URL: "mongodb:27017"
      ADMIN_DB: "admin"
      DEFAULT_DB: "pipeline"
